TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
T    ##########                                            T
T  ############                                            T
T  ########                                           #    T
T  #######                  TT                     ####    ]
T    ####              TT TTTTT                  ######    T
T    ####            TTTTTTTTT                  #######    T
T                   TTTTT                     #########    T
T                  TTTT                     ###########    T
T                TTTTT                    ############     T
T                TTT                ##    ##########       T
T                                   #############          T
T                                    #########             T
T                                                          T
T                                                          T
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT