TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
T                         #                             #            T
T                                    #          ##########           T
T                                 TT        #############         T  T
[     #         #          ##   TTTTT     ##############        TTT  T
T                         ###  TT TT      ###########     ## TTTTT   T
T                        # # TTTTTTT  ##############    ####TT  TT   T
T              #     # #####TTT TTT#######       #  #####  TT  TT    T
T   #                ###################          ###    TTTTTT      T
T                    ##################      TTTTTT TTTTTTT          T
T         #        #######TTTTT          TTTTTTTT     TT  #####      T
T                 #####   TTTT         TTTTT           TT##      ### T
T            ######### TTTTT          TTTT              ##T     #####T
T           #####TTTTTTTTTTTTTTT TTTTTTT                #TT   #######T
T           #TTTTTTTTTTTT      TTTT                     #TT #########T
T    #       TTTTTTTT                             T T  T# ###  ##### T
T         TTTTT T                            T TTT   TTTT########### T
T                                           TTTTTTTTTT   ########### T
T                                                 ################## ]
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT